### PR TITLE
docs: Update UG v1.1

### PR DESCRIPTION
**Pull request by freshcabbage123**
## What type of PR is this? (check all applicable)

-   [ ] Refactor
-   [ ] Feature
-   [ ] Bug Fix
-   [ ] Optimization
-   [x] Documentation Update

## Description

* Replace listTasks and addPerson output
* listPerson is unchanged as it follows original UI

## Related Tickets & Documents

-   Related Issue #38 

## Added/updated tests?

_We encourage you to keep the code coverage percentage at 75% and above for new changes._

-   [ ] Yes
-   [x] No, and this is why: no code change to main application
-   [ ] No, there are UI changes that I'm unable to cover.
-   [ ] I need help with writing tests

### CODE REVIEW

**Review by jiakai-17 — APPROVED** [review]
LGTM

**Review by HugeNoob — COMMENTED** [review]
Small grammar nit: Are we planning to stick to `listTask` or `listTasks`? 

It's `listTask` in Notion, and also not consistent in your changes. Same concern for `listPerson` vs `listPersons`.

Would it also be good to add a Ui mockup for `listPerson`? Though I would agree if you think it's not very meaningful.

**Comment by freshcabbage123** [comment]
> Small grammar nit: Are we planning to stick to `listTask` or `listTasks`?
> 
> It's `listTask` in Notion, and also not consistent in your changes. Same concern for `listPerson` vs `listPersons`.
> 
I suppose we should change the 'listing' commands to plural to better reflect its purpose of showing multiplicity? 

> Would it also be good to add a Ui mockup for `listPerson`? Though I would agree if you think it's not very meaningful.

Yep, I thought the original mockup for AB3 would be largely similar to a new Ui mockup for `listPersons` so i didn't think it was very necessary.

**Review by pra-navi — APPROVED** [review]
LGTM, good work!

**Pull request merged**
