### PR TITLE
ci: Implement automatic releases

### PR DESCRIPTION
**Pull request by jiakai-17**
* Automatically creates releases with built .jar file
* On change to master, a new pre-release is created with title: Development Build
* ~On a new semver-looking tag, a new release is created~

### CODE REVIEW

**Comment by HugeNoob** [comment]
Thanks for looking into this. A few points of clarification:

1. Could you elaborate on the use cases we have for auto-deployment?
2. I notice that you're using https://github.com/marvinpinto/action-automatic-releases. Do we have any use cases for pre-release vs tagged releases? Perhaps we can just keep pre-release deployments.
3. I'm not too sure that CS2103T follows semantic versioning. In the worst case, inconsistent versioning practices may result in poor tracking by the dashboards or confusion among other users. Do we still want this CI given this risk?  
3.1 For example, the [website](https://nus-cs2103-ay2324s1.github.io/website/admin/tp-w8.html) seems to recommend versioning that don't align with typical semantic versioning conventions.
image

**Comment by jiakai-17** [comment]
Thank you for your feedback!

>     1. Could you elaborate on the use cases we have for auto-deployment?

One use case I can think of is that we do not need to manually clone the repo and execute the `gradlew build` command on our end on every commit. Instead, we can download the prebuilt .jar file and run it immediately.


>     2. I notice that you're using https://github.com/marvinpinto/action-automatic-releases. Do we have any use cases for pre-release vs tagged releases? Perhaps we can just keep pre-release deployments.
>     3. I'm not too sure that CS2103T follows semantic versioning. In the worst case, inconsistent versioning practices may result in poor tracking by the dashboards or confusion among other users. Do we still want this CI given this risk?
>        3.1 For example, the [website](https://nus-cs2103-ay2324s1.github.io/website/admin/tp-w8.html) seems to recommend versioning that don't align with typical semantic versioning conventions.
>        image

Good catch! I also saw that we will have to `git tag v1.2` in [week 9](https://nus-cs2103-ay2324s1.github.io/website/admin/tp-w9.html#2-wrap-up-v1-2). This will cause the `tagged-release` CI to fail as it does not follow semver strictly.

For now, I think we can still keep the pre-release versions like you mentioned, and manually create releases for major milestones (v1.2, v1.3 etc). However, the .jar binary in the pre-release will be overwritten with each CI run.

**Comment by jiakai-17** [comment]
> > One use case I can think of is that we do not need to manually clone the repo and execute the `gradlew build` command on our end on every commit. Instead, we can download the prebuilt .jar file and run it immediately.
> 
> Do pre-release jar files serve any purpose? I'm not sure anyone will be using them. I'm okay with adding this change, as long as it doesn't mess up the dashboard tracking. Also, how does the initial versioning work, since no version number has been specified yet?

I guess it makes it easier us to quickly get the latest build of our master branch.

Regarding the versioning, no version number is implemented, so it will not affect any version numbers and tracking by the CS2103T scripts.

You can see my experimentation here on a separate repo: https://github.com/NUSTutors/tp-test-ci

**Review by HugeNoob — APPROVED** [review]
Alright, LGTM then. Thanks for the changes.

**Pull request merged**
