### PR TITLE
docs: Update readme UI 

### PR DESCRIPTION
**Pull request by m1oojv**
## What type of PR is this? (check all applicable)

-   [ ] Refactor
-   [ ] Feature
-   [ ] Bug Fix
-   [ ] Optimization
-   [x] Documentation Update

## Description

-   Add image of Ui mockup to README.

## Related Tickets & Documents

-   Addresses https://github.com/AY2324S1-CS2103T-T10-2/tp/issues/37

## Added/updated tests?

_We encourage you to keep the code coverage percentage at 75% and above for new changes._

-   [ ] Yes
-   [x] No, and this is why: check [link](https://github.com/m1oojv/tp/tree/docs/readme-ui)
-   [ ] No, there are UI changes that I'm unable to cover.
-   [ ] I need help with writing tests

### CODE REVIEW

**Comment by HugeNoob** [comment]
Hmm there are some unrelated changes in this PR. Could you rebase `upstream master` for this branch to separate the other documentation updates? Thanks!

**Review by HugeNoob — CHANGES_REQUESTED** [review]
Forgot to leave my previous comment as a request. Could you rebase this branch to isolate the readme-ui changes?

**Review by jiakai-17 — CHANGES_REQUESTED** [review]
A few nits about the Ui

1. According to the [task description](https://nus-cs2103-ay2324s1.github.io/website/schedule/week7/project.html#2-update-project-website-aboutus-readme), the new Ui.png should be "roughly the same height x width proportions as the original one". However, the new image seems to be larger than the original one. Perhaps you could resize it to a similar dimension?

2. Perhaps you could add our app name into the title bar?

**Review by jiakai-17 — APPROVED** [review]
LGTM for a mockup!

**Comment by pra-navi** [comment]
Considering they requested for the width to be the same as well, is there a way to ensure that as well?

**Comment by m1oojv** [comment]
> Considering they requested for the width to be the same as well, is there a way to ensure that as well?

I think considering that we are adding another column . I don't think we should have the same width. Anyways the increase in width is not as significant

**Comment by m1oojv** [comment]
Updated the wireframe to have our app name in title bar and size requirements that we need to resize to whenever we screenshot. [Link](https://docs.google.com/presentation/d/1fXBqhAU6SSoSZdYVog3G9v5H6gXFMCzPAQ2BjzzWzM4/edit#slide=id.g283c3f50b29_0_0)
Here is the [link](https://www.xconvert.com/resize-png) i used to resize the UI

**Review by HugeNoob — APPROVED** [review]

**Pull request merged**
