### PR TITLE
feat: Implement addPerson command

### PR DESCRIPTION
**Pull request by freshcabbage123**
## What type of PR is this? (check all applicable)

-   [ ] Refactor
-   [X] Feature
-   [ ] Bug Fix
-   [ ] Optimization
-   [ ] Documentation Update

## Description

-   Implemented addPerson command

## Related Tickets & Documents

-   Related Issue #50 

## Added/updated tests?

_We encourage you to keep the code coverage percentage at 75% and above for new changes._

-   [X] Yes
-   [ ] No, and this is why: _please replace this line with details on why tests
        have not been included_
-   [ ] No, there are UI changes that I'm unable to cover.
-   [ ] I need help with writing tests

### CODE REVIEW

**Comment by freshcabbage123** [comment]
Do let me know if you guys think it's better to remove code for `add` command. Currently, it is still in the codebase.

**Review by HugeNoob — APPROVED** [review]
Seems like it's entirely a find-and-replace. Don't think there's any new functionality we need so LGTM.

**Review by jiakai-17 — CHANGES_REQUESTED** [review]
https://github.com/freshcabbage123/tp/blob/a019e4fe44fc8c20a21f411977f007ee10478ed9/src/test/java/seedu/address/logic/parser/EditCommandParserTest.java#L169C1-L169C1

Minor nit: Change this reference to AddPersonCommandParser in the comment.

**Review by jiakai-17 — APPROVED** [review]
LGTM. Thanks for the changes!

**Pull request merged**
